update script fail early

diff --git a/bin/upgrade b/bin/upgrade
--- a/bin/upgrade
+++ b/bin/upgrade
@@ -1,4 +1,5 @@
 #!/usr/bin/env zsh
+set -e # stops on first failure
 
 echo "upgrading installed packages..."
 sudo rm -rf /tmp/yaourt-tmp-$USER /tmp/makepkg
